micronaut:
  application:
    name: keymanagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix?useTimezone=true&serverTimezone=UTC
    driveClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    dialect: org.hibernate.dialect.MySQL8InnoDBDialect

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

itau:
  uri: http://localhost:9091/api/v1